package de.tuhrig.neo4j.domain.location;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.support.UUIDStringGenerator;

/**
 * What to see here:
 * <p>
 * - An entity with an autogenerated UUID as the main key
 */
@Node("location")
@Data
@NoArgsConstructor // For the Neo4j API
@EqualsAndHashCode(onlyExplicitlyIncluded = true) // Just the business key as the identity!
public class Location {

    @Id
    @EqualsAndHashCode.Include
    @GeneratedValue(UUIDStringGenerator.class)
    private String id;

    private String street;
    private String houseNumber;
    private String city;

    public Location(
            String street,
            String houseNumber,
            String city
    ) {
        this.street = street;
        this.houseNumber = houseNumber;
        this.city = city;
    }
}
